# Use an official MySQL image as the base image
FROM mysql:latest

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=rPassw0rd
ENV MYSQL_DATABASE=wordpressdb
ENV MYSQL_USER=wordpressuser
ENV MYSQL_PASSWORD=password
