version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    volumes:
      - db_data:/var/lib/mysql
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile.wordpress
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
volumes:
  db_data:
  wp_data:
