# Use an official WordPress image as the base image
FROM wordpress:latest

# Set environment variables for MySQL database connection
ENV WORDPRESS_DB_HOST=db
ENV WORDPRESS_DB_USER=wordpressuser
ENV WORDPRESS_DB_PASSWORD=password
ENV WORDPRESS_DB_NAME=wordpressdb

# Expose port 80 for the web server
EXPOSE 80

