version: '3.3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    networks:
      - my_custom_network
    volumes:
      - db_data:/var/lib/mysql  # Add volume for the 'db' service

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8080:80"
    restart: always
    env_file:
      - .env
    networks:
      - my_custom_network
    volumes:
      - wordpress_data:/var/www/html  # Add volume for the 'wordpress' service

networks:
  my_custom_network:

volumes:
  db_data: {}          # Define volume for the 'db' service
  wordpress_data: {}   # Define volume for the 'wordpress' service

